# Generated by Django 5.2.8 on 2025-11-11 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_trainer_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('P', 'Planta'), ('L', 'Lagartija'), ('T', 'Tierra'), ('F', 'Fuego'), ('A', 'Agua')], max_length=30),
        ),
    ]
